### ISSUE TITLE
Data not showing on 'Browse important pastes' tab

### ISSUE THREAD

**Issue by intoxe** [CIRCL/AIL-framework#109]
Hello,
I have some pastes containing a mail address, I know this mail address has been received by AIL because I can retrieve it in the "Terms frequency: Management interface" tab. But my 'Browse important pastes' tab is still empty (I am using pystemon to feed AIL):
![capture5](https://cloud.githubusercontent.com/assets/3937759/23262171/11e03e2c-f9da-11e6-9e9b-a53e91679705.PNG)

Thank you.

**Comment by mokaddem** [comment]
Hi, 
Due to a bug introduced in d4da3a316f18f36f9c61e7c0a5cc601898fa489a, the Categ module was not working correctly. It has been fixed in 26eb5fdff08487bb6bd379a3e41362f0520dee90.
Also, the logic concerning the mail has been updated. Now, a matched email address will be shown in "Browse important pastes" only if the number of matched mail > critical value (default 10).

Thank you for pointing the problem out!
