### ISSUE TITLE
import_dir.py not working

### ISSUE THREAD

**Issue by cudeso** [CIRCL/AIL-framework#124]
Hi,

When I use the import_dir.py on a directory containing files with username/passwords (in fact this one https://pastebin.com/2zXVNGrt) the processing via import_dir does not return any errors but 
- dashboard does not give feedback on any queues running
- information can not be retrieved afterwards in Important pasties/mail
Tried this with the VM from https://www.circl.lu/services/ail-training-materials/#ail-virtual-machine

When I tried this with a manual setup of AIL (not VM from training-material) I saw the graphs for Qeues Monitor and processed pastes changing but I could not retrieve the results either.

kr,

koen

**Comment by mokaddem** [comment]
Hi,

Can you please check that you are subscribed to your local address while importing with __import_dir.py__? This can be found in your __config.cfg__ file, in ```[ZMQ_Global]->address```

Also, #138 added some 'feedback' in case of error and the possibility to feed raw files.

Thanks for your feedback!

**Comment by garanews** [comment]
Hello,
I have the same issue. The config.cfg under AIL-framework/bin/packages is set as default:
[ZMQ_Global]
#address = tcp://crf.circl.lu:5556
address = tcp://127.0.0.1:5556
channel = 102
bind = tcp://127.0.0.1:555

In the log I see:
[2017-08-30 09:07:29.477156] INFO: Script: Mixer; ; ; ;mixer_all All_feeders Processed 0 paste(s) in 30sec
[2017-08-30 09:08:00.567433] INFO: Script: Mixer; ; ; ;mixer_all All_feeders Processed 0 paste(s) in 30sec
[2017-08-30 09:08:31.666527] INFO: Script: Mixer; ; ; ;mixer_all All_feeders Processed 1 paste(s) in 30sec
[2017-08-30 09:08:31.676981] INFO: Script: Mixer; ; ; ;mixer_import_dir import_dir Processed 1 paste(s) in 30sec
[2017-08-30 09:08:31.687391] INFO: Script: Mixer; ; ; ;mixer_import_dir import_dir Duplicated 0 paste(s) in 30sec

But in the console nothing appears.
I have not installed pystemon : is this mandatory for the manual import?
I'm asking because in the how to I read:
For the moment, there are three different ways to feed AIL with data:
1. Be a collaborator of CIRCL and ask to access our feed. It will be sent to the static IP your are using for AIL.
2. You can setup pystemon and use the custom feeder provided by AIL (see below).
3. You can feed your own data using the ./bin/import_dir.py script.

Thanks

**Comment by mokaddem** [comment]
Hi,
Pystemon is not needed to manually feed data to AIL.
If you want to feed data from a folder, only ```bin/import_dir.py``` is necessary.
By the console, do you mean 'logs' in the dashboard webpage?

**Comment by Terrtia** [comment]
Fixed with ebad2af1ae5524e75caa62ec616d82cfda13c15e
We close the issue, feel free to reopen if the issue persists.
