### ISSUE TITLE
Minimal Configuration

### ISSUE THREAD

**Issue by FafnerKeyZee** [CIRCL/AIL-framework#252]
Hey,

I'm starting to test AIL to run it in production, so I've a small question:
What is the minimal hardware Configuration ? and what is the recommended hardware ?

Best regards,

**Comment by mokaddem** [comment]
Hello,
It depends on the quantity of data you want to process, the type of data and the number of analysis modules you start.

By default, AIL starts every available modules. It's up to you to comment out unwanted scripts.

I would say that the minimum configuration is at least 2 CPUs and 8GB of memory. But the software can support much more (by design). The recommended would be 4 to 8 CPUs and 16 to 32GB.

We are planning to make 2 types of installer/launcher:
- a basic one with the minimum required components to run the framework
- an advanced one with all modules activated

**Comment by certrik** [comment]
@adulau 
Sorry to bother but I didn't find any other source. Is this answer still valid or have the requirements changed?

**Comment by adulau** [comment]
I think the requirements are a bit bigger (still very variable with the stream that you'll ingest). But having 16GB of memory is really a minimum nowadays. I hope this helps.
