### ISSUE TITLE
Installing on Ubuntu 16.04.05 LTS

### ISSUE THREAD

**Issue by aiacopini** [CIRCL/AIL-framework#293]
Hi Mate,
just a fresh install, when I try to launch Flask I got the error:
root@XXXX/opt/AIL-framework/var/www# ./Flask_server.py
Traceback (most recent call last):
  File "./Flask_server.py", line 4, in <module>
    import redis
ImportError: No module named 'redis'

Launch.sh has been executed activating all ten options.

All the best,

Andrea

**Comment by Terrtia** [comment]
hey @aiacopini !

Can you please try ``LAUNCH.sh -l`` ?

**Comment by SteveClement** [comment]
I just tested this on my Ubuntu 16.04.5 setup and it works just fine.

My bet is that the virtualenvironment is not present.

Also, do not launch it manually. As @Terrtia suggested, use the LAUNCH.sh script.

This in turn will create the necessary _screen_ sessions.

And finally, do not run AIL as root, this is potentially dangerous.

You are ingesting random data from potentially random site.

**Comment by DGoKali** [comment]
Hi Guys,
I am getting an error "Please make sure you have a AIL-framework environment, au revoir", also the ARDB NEVER starts?? Appreciate, if anyone could help installing the framework. 
Thanks guys!
Best,

**Comment by Terrtia** [comment]
Hi @DGoKali !

It seem like the installation isn't complete.

Can you please relaunch the installer ?
Did you encounter any errors ?

**Comment by phoenixml** [comment]
Hi @Terrtia  I am having the same issue since this still ticket still open I will use it to share my error:
  CC       db/db_impl/db_impl_compaction_flush.o
db/db_impl/db_impl_compaction_flush.cc: In member function ‘rocksdb::Status rocksdb::DBImpl::CompactFilesImpl(const rocksdb::CompactionOptions&, rocksdb::ColumnFamilyData*, rocksdb::Version*, const std::vector<std::__cxx11::basic_string<char> >&, std::vector<std::__cxx11::basic_string<char> >*, int, int, rocksdb::JobContext*, rocksdb::LogBuffer*, rocksdb::CompactionJobInfo*)’:
db/db_impl/db_impl_compaction_flush.cc:1040:21: error: loop variable ‘newf’ creates a copy from type ‘const std::pair<int, rocksdb::FileMetaData>’ [-Werror=range-loop-construct]
 1040 |     for (const auto newf : c->edit()->GetNewFiles()) {
      |                     ^~~~
db/db_impl/db_impl_compaction_flush.cc:1040:21: note: use reference type to prevent copying
 1040 |     for (const auto newf : c->edit()->GetNewFiles()) {
      |                     ^~~~
      |                     &
db/db_impl/db_impl_compaction_flush.cc: In member function ‘void rocksdb::DBImpl::NotifyOnCompactionBegin(rocksdb::ColumnFamilyData*, rocksdb::Compaction*, const rocksdb::Status&, const rocksdb::CompactionJobStats&, int)’:
db/db_impl/db_impl_compaction_flush.cc:1140:21: error: loop variable ‘newf’ creates a copy from type ‘const std::pair<int, rocksdb::FileMetaData>’ [-Werror=range-loop-construct]
 1140 |     for (const auto newf : c->edit()->GetNewFiles()) {
      |                     ^~~~
db/db_impl/db_impl_compaction_flush.cc:1140:21: note: use reference type to prevent copying
 1140 |     for (const auto newf : c->edit()->GetNewFiles()) {
      |                     ^~~~
      |                     &
cc1plus: all warnings being treated as errors
make[2]: *** [Makefile:2117: db/db_impl/db_impl_compaction_flush.o] Error 1
make[2]: Leaving directory '/home/ubuntu/ail-framework/ardb/deps/rocksdb-6.8.1'
make[1]: *** [Makefile:411: /home/ubuntu/ail-framework/ardb/src/../deps/rocksdb-6.8.1/librocksdb.a] Error 2
make[1]: Leaving directory '/home/ubuntu/ail-framework/ardb/src'
make: *** [Makefile:4: all] Error 2

I relaunch the installer lets see how it will goes same issue you guidance is appreciated.

**Comment by Terrtia** [comment]
This is an ARDB install issue.  Fixed in AIL v5.0
The database has been migrated from ARDB to Kvrocks.
