### ISSUE TITLE
Onion Screenshots

### ISSUE THREAD

**Issue by Malwar3Ninja** [CIRCL/AIL-framework#367]
Team, is there a way to disable automatic screenshot of onion pages ?

**Comment by Terrtia** [comment]
hey @Malwar3Ninja 

Thank you for your feedback !

Should be fixed with 09ecc4d93facb135fdfa7218706f594698de8efa
 
I added some new fields in ``config.cfg``
You need to launch [Update-conf.py](https://github.com/CIRCL/AIL-framework/blob/master/bin/Update-conf.py) and set ``default_crawler_png`` to False
