### ISSUE TITLE
Installation Issues & Starting the Flask server

### ISSUE THREAD

**Issue by madhuakula** [CIRCL/AIL-framework#79]
Hello Team,

Really thanks for the great project. Do you have any better documentation for installation (or) any recommendations to choose which version of distro will work out of the box.

**Comment by Rafiot** [comment]
Hello, 

right now, no, we don't have any better documentation. 

The recommended OS is Ubuntu 14.04 or 16.04, and it should pretty much work out-of-the-box. If it doesn't, please let us know.

**Comment by adrianduff** [comment]
Hi,

I'm also having problems getting the install to work properly.  I have tried in both Kali and Ubuntu 16.04.

I used the recommended ./installing-deps.sh script but i ran into this issue..

`Collecting http://adns-python.googlecode.com/files/adns-python-1.2.1.tar.gz (from -r pip_packages_requirement.txt (line 43))
  HTTP error 404 while getting http://adns-python.googlecode.com/files/adns-python-1.2.1.tar.gz
  Could not install requirement http://adns-python.googlecode.com/files/adns-python-1.2.1.tar.gz (from -r pip_packages_requirement.txt (line 43)) because of error 404 Client Error: Not Found for url: http://adns-python.googlecode.com/files/adns-python-1.2.1.tar.gz
Could not install requirement http://adns-python.googlecode.com/files/adns-python-1.2.1.tar.gz (from -r pip_packages_requirement.txt (line 43)) because of HTTP error 404 Client Error: Not Found for url: http://adns-python.googlecode.com/files/adns-python-1.2.1.tar.gz for URL http://adns-python.googlecode.com/files/adns-python-1.2.1.tar.gz
`
I navigated to the link at it looks like the file is missing....could you please fix this up / let me know if I am making a mistake??

**Comment by johnbeers** [comment]
Hi adrianduff,

I had the same problem. The link is wrong. The following is ok:

https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/adns-python/adns-python-1.2.1.tar.gz

**Comment by Rafiot** [comment]
I updated the download link.
