### ISSUE TITLE
Issues with big files containing tons of UUIDs

### ISSUE THREAD

**Issue by Rafiot** [CIRCL/AIL-framework#91]
Tokenize and Sentiment analysis were stuck on our platform because of huge files containing huge lists of UUIDs (more than one million per file).

Some examples:
```
teruteru128_cceb0e34fb4153d454596c03f953d8f6
teruteru128_292c5a69b229bfbd2875240ca1587755
teruteru128_f01fa322f03f3c341421a0c4bab5f508
teruteru128_17bf2ebc3b47c9846ec0d5248e34f55a
teruteru128_968d53c6287ed0435e1c205c01d40e64
```

**Comment by adulau** [comment]
The issue is still and it's due to the famous regexp used for the tokenization.

https://github.com/CIRCL/AIL-framework/blob/master/bin/packages/Paste.py#L332

~~~~python
tokenizer = RegexpTokenizer('[\&\~\:\;\,\.\(\)\{\}\|\[\]\\\\/\-/\=\'\"\%\$\?\@\+\#\_\^\<\>\!\*\n\r\t\s]+',
gaps=True, discard_empty=True)
~~~~

Maybe having a pre-regexp matching with an extraction of a random sample could help. If we have a set of UUID in the sample, we discard such input. It's not perfect...
